### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [cobyj33/Web-App-DAW#1]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under the [DAWs section](https://github.com/forart/HyMPS/blob/main/DAWs.md) - [Web/online sub](https://github.com/forart/HyMPS/blob/main/DAWs.md#webonline-)), can you please fix licensing terms for it ?

Our "problem" is that does not generates a correct badge:

![](https://flat.badgen.net/github/license/cobyj33/Web-App-DAW/?label=LICENSE)
(generate url: https://flat.badgen.net/github/license/cobyj33/Web-App-DAW/?label=LICENSE)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration (and therefore evolution) between developers of listed projects.

Thanks in advance.

**Comment by cobyj33** [comment]
Thank you, I have just added the MIT License to the repository.

**Comment by MarcoRavich** [comment]
First of all, thanks for the timely fix!

As you can see (above too) the badge is generated correctly now.

Thanks again and, if you like/need, let us know (by replying to [our discussions](https://github.com/forart/HyMPS/discussions)) how we can support listed projects.

Last but not least, Happy New Year !
